# Generated by Django 5.0.6 on 2024-08-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_materiales_comentarios_priv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('fecha_edit', models.DateTimeField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.actividades')),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.alumno')),
                ('id_profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.profesor')),
            ],
        ),
    ]
