# Generated by Django 5.0.6 on 2024-08-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_actividades_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales_comentarios_priv',
            name='id_material',
        ),
        migrations.AddField(
            model_name='materiales_comentarios_priv',
            name='id_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataforma.actividades'),
            preserve_default=False,
        ),
    ]
