# Generated by Django 5.0.6 on 2024-08-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_entregas_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignar_actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('entregada', models.BooleanField(default=False)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.actividades')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.alumno')),
            ],
        ),
    ]
