# Generated by Django 5.0.6 on 2024-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_asignar_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignar_actividad',
            name='calificacion',
            field=models.IntegerField(null=True),
        ),
    ]
